import { type GenLayerChain, type GenLayerClient, type TransactionHash } from "genlayer-js/types";
import { address, alter, deployedSource, localSource, readFinal, record, requiredContract, runDeployment, sha256Ascii, type Stage, stableJson, txHash, uint, waitReceipt } from "../support/runtime.js";

const CONFIG = { prefix: "CUTOFFCHRONOLOGY", project: "CutoffChronologyResolver", contractFile: "contracts/cutoff_chronology_resolver.py", sourceSha256: "EF483235B85080B8C6245726053DA9EF89A34230C94A42C3A004EE35CF8DF98F" } as const;
const CHRONOLOGY_SCHEMA = "cutoffchronologyresolver/chronology/v1"; const AUDIT_SCHEMA = "cutoffchronologyresolver/audit/v1"; const FINGERPRINT_SCHEMA = "cutoffchronologyresolver/fingerprint/v1";
const CUTOFF = 1_900_000_000;
const FIXTURE = { proposition: "Did the registered corporate filing become effective before the specified cutoff?", timestampRule: "Use the filing's explicitly stated effective Unix time, not its later publication or discovery time. Strictly before means event_time_unix is less than cutoff_unix.", evidence: `The registered filing states effective_time_unix=1899990000. The official portal states publication_time_unix=1900010000. Both values refer to this exact filing.` } as const;

function fingerprint(policy: number, creator: string, key: string): string { const normalized = address(creator, "creator"); return sha256Ascii({ schema: FINGERPRINT_SCHEMA, policy_version: policy, chronology_id: `${normalized}:${key}`, creator: normalized, chronology_key: key, proposition: FIXTURE.proposition, cutoff_unix: CUTOFF, timestamp_rule: FIXTURE.timestampRule, evidence_text: FIXTURE.evidence }); }
async function verifyPolicy(client: GenLayerClient<GenLayerChain>, target: `0x${string}`, policy: number, signer: string): Promise<void> { const value = record(await readFinal(client, target, "get_policy"), "policy"); if (address(value.owner, "owner") !== address(signer, "signer") || uint(value.policy_version, "policy") !== policy || value.purpose !== "BOUNDED_EVENT_CHRONOLOGY_NOT_GENERAL_ORACLE" || value.chronology_schema !== CHRONOLOGY_SCHEMA || value.audit_schema !== AUDIT_SCHEMA || value.fingerprint_schema !== FINGERPRINT_SCHEMA || value.strict_before_semantics !== true || value.event_at_cutoff_is_after !== true || value.creator_only_resolution !== true || value.external_evidence_authenticity_verified !== false) throw new Error("policy read-back failed"); }

async function smoke(client: GenLayerClient<GenLayerChain>, stage: Stage, policy: number, retries: number, interval: number) {
  const target = requiredContract(CONFIG.prefix); const signer = address(client.account?.address, "signer"); localSource(CONFIG); const sourceHash = await deployedSource(client, target, CONFIG.sourceSha256); await verifyPolicy(client, target, policy, signer);
  const key = stage === "studionet" ? "STUDIO-FILING-CUTOFF-20260812" : "BRADBURY-FILING-CUTOFF-20260812"; const chronologyId = `${signer}:${key}`; const expected = fingerprint(policy, signer, key);
  const resume = process.env.CUTOFFCHRONOLOGY_SMOKE_RESUME === "1";
  if (resume && stage !== "bradbury") throw new Error("smoke resume is restricted to Bradbury recovery");
  let registration: TransactionHash | undefined;
  if (!resume) { registration = txHash(await client.writeContract({ address: target, functionName: "register_chronology", args: [key, FIXTURE.proposition, CUTOFF, FIXTURE.timestampRule, FIXTURE.evidence], value: 0n })); console.log(`Smoke registration transaction: ${registration}`); await waitReceipt(client, registration, "FINALIZED", retries, interval); }
  else { console.log("Smoke registration: RESUME_EXISTING_FINALIZED"); }
  const stored = record(await readFinal(client, target, "get_chronology", [chronologyId]), "chronology"); if (stored.schema !== CHRONOLOGY_SCHEMA || stored.chronology_id !== chronologyId || stored.chronology_fingerprint !== expected || uint(stored.cutoff_unix, "cutoff") !== CUTOFF || address(stored.creator, "creator") !== signer) throw new Error("registration read-back failed");
  let auditHash: TransactionHash | undefined; if (await readFinal(client, target, "is_resolved", [chronologyId]) !== true) { auditHash = txHash(await client.writeContract({ address: target, functionName: "resolve_chronology", args: [chronologyId], value: 0n })); console.log(`Smoke audit transaction: ${auditHash}`); await waitReceipt(client, auditHash, "FINALIZED", retries, interval); }
  const audit = record(await readFinal(client, target, "get_audit", [chronologyId]), "audit"); const exact = await readFinal(client, target, "matches_verdict", [chronologyId, expected, "BEFORE_CUTOFF"]); const changed = await readFinal(client, target, "matches_verdict", [chronologyId, alter(expected), "BEFORE_CUTOFF"]);
  if (audit.schema !== AUDIT_SCHEMA || audit.chronology_fingerprint !== expected || audit.finding !== "EVENT_FOUND" || audit.verdict !== "BEFORE_CUTOFF" || uint(audit.event_time_unix, "event time") !== 1_899_990_000 || uint(audit.publication_time_unix, "publication time") !== 1_900_010_000 || uint(audit.issue_mask, "issue mask") !== 0 || stableJson(audit.issue_codes) !== "[]" || exact !== true || changed !== false) throw new Error("audit result failed exact checks");
  console.log(`Smoke ID: ${chronologyId}`); console.log(`Smoke fingerprint: ${expected}`); console.log("Smoke verdict: BEFORE_CUTOFF; issue mask 0"); console.log("Exact gate: true; altered gate: false"); return { target, sourceHash, registration, auditHash, chronologyId, fingerprint: expected, verdict: audit.verdict, eventTimeUnix: audit.event_time_unix, issueMask: 0, exact, changed };
}
export default async function main(client: GenLayerClient<GenLayerChain>) { return runDeployment(client, CONFIG, verifyPolicy, smoke); }
